<!DOCTYPE html>
<html {{language_attributes}}>
  <head>
    <meta charset="{{charset}}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{title}}</title>
    
    {% for style in styles %}
        <link href="{{style}}" rel="stylesheet">
    {% endfor %}
    {{wp_head}}
  </head>
  <body {{body_class}}>